# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project
# SPDX-FileCopyrightText: Copyright contributors to the Aphrodite Engine project

"""Generate user reference pages from Sonar's source of truth."""

from __future__ import annotations

import argparse
import ast
from pathlib import Path

import regex as re

ROOT = Path(__file__).resolve().parents[2]
DOCS = ROOT / "docs/src/content/docs/reference"
REGISTRY = ROOT / "aphrodite/model_executor/models/registry.py"
QUANTIZATION = ROOT / "aphrodite/model_executor/layers/quantization/__init__.py"
PLATFORMS = {
    "AMD ROCm": ROOT / "aphrodite/platforms/rocm.py",
    "Intel XPU": ROOT / "aphrodite/platforms/xpu.py",
}
MODEL_GROUPS = {
    "_TEXT_GENERATION_MODELS": "Text generation",
    "_EMBEDDING_MODELS": "Embedding",
    "_LATE_INTERACTION_MODELS": "Late interaction",
    "_REWARD_MODELS": "Reward",
    "_TOKEN_CLASSIFICATION_MODELS": "Token classification",
    "_SEQUENCE_CLASSIFICATION_MODELS": "Sequence classification",
    "_MULTIMODAL_MODELS": "Multimodal",
    "_SPECULATIVE_DECODING_MODELS": "Speculative decoding",
    "_TRANSFORMERS_SUPPORTED_MODELS": "Transformers backend",
}


def user_facing_text(text: str) -> str:
    """Apply Sonar branding without changing commands or code identifiers."""
    text = re.sub(
        r"\n*API docs: <?https://docs\.aphrodite\.ai/[^\s>]+>?\n*",
        "\n",
        text,
    )
    text = text.replace(
        "https://docs.aphrodite.ai/en/latest/configuration/serve_args.html",
        "https://sonar.dphn.ai/reference/server-arguments/",
    )
    text = re.sub(
        r"\[TPU\]\(https://docs\.aphrodite\.ai/projects/tpu/en/latest/\)",
        "TPU",
        text,
    )
    parts = re.split(r"(`[^`]*`)", text)
    for index in range(0, len(parts), 2):
        parts[index] = parts[index].replace("Aphrodite Engine", "Sonar")
        parts[index] = parts[index].replace("Aphrodite", "Sonar")
    text = "".join(parts).strip()
    text = re.sub(r"(?m)^\* ", "- ", text)
    text = re.sub(r"(?m)(?<!\n)\n(?=- )", "\n\n", text)
    text = text.replace("Supported mode:\n", "Supported mode:\n\n")
    text = re.sub(r"\b((?:processed|raw)_\*)", r"`\1`", text)

    def wrap_url(match: re.Match) -> str:
        url = match.group()
        suffix = ""
        while url.endswith((".", ",")):
            suffix = url[-1] + suffix
            url = url[:-1]
        return f"<{url}>{suffix}"

    text = re.sub(r"(?<!\]\()(?<!<)https://[^\s)]+", wrap_url, text)
    return re.sub(r"\n{3,}", "\n\n", text)


def parse_assignments(path: Path) -> dict[str, ast.AST]:
    tree = ast.parse(path.read_text())
    assignments = {}
    for node in tree.body:
        if isinstance(node, (ast.Assign, ast.AnnAssign)):
            target = node.targets[0] if isinstance(node, ast.Assign) else node.target
            if isinstance(target, ast.Name) and node.value is not None:
                assignments[target.id] = node.value
    return assignments


def literal_assignment(path: Path, name: str):
    tree = ast.parse(path.read_text())
    for node in ast.walk(tree):
        if isinstance(node, ast.Assign):
            if any(isinstance(target, ast.Name) and target.id == name for target in node.targets):
                return ast.literal_eval(node.value)
        elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name) and node.target.id == name:
            return ast.literal_eval(node.value)
    raise RuntimeError(f"Could not find {name} in {path}")


def frontmatter(title: str, description: str) -> str:
    return f"---\ntitle: {title}\ndescription: {description}\n---\n\n"


def model_reference() -> str:
    from aphrodite.model_executor.models import registry

    sections = [
        frontmatter(
            "Supported models",
            "Model architectures that the current Sonar source tree registers.",
        ),
        "<!-- Generated by tools/docs/generate_user_reference.py. Do not edit. -->\n\n",
        "Sonar reads the `architectures` field from a model's `config.json` file. "
        "The value must match an architecture in these tables. A compatible "
        "Transformers implementation can also use the Transformers backend.\n\n",
    ]
    total = 0
    for assignment, title in MODEL_GROUPS.items():
        models = getattr(registry, assignment)
        total += len(models)
        sections.extend(
            [
                f"## {title}\n\n",
                "| Architecture | Implementation |\n",
                "| --- | --- |\n",
            ]
        )
        for architecture, implementation in sorted(models.items()):
            module, class_name = implementation
            sections.append(f"| `{architecture}` | `{module}:{class_name}` |\n")
        sections.append("\n")
    sections.insert(
        3,
        f"The current registry contains **{total} architecture entries** in the user-facing categories below.\n\n",
    )
    return "".join(sections)


def quantization_methods() -> list[str]:
    tree = ast.parse(QUANTIZATION.read_text())
    for node in ast.walk(tree):
        if (
            isinstance(node, ast.Assign)
            and any(isinstance(target, ast.Name) and target.id == "QuantizationMethods" for target in node.targets)
            and isinstance(node.value, ast.Subscript)
        ):
            return [ast.literal_eval(item) for item in node.value.slice.elts]
    raise RuntimeError("Could not find QuantizationMethods")


def quantization_config_classes() -> dict[str, str]:
    tree = ast.parse(QUANTIZATION.read_text())
    for node in ast.walk(tree):
        if (
            isinstance(node, ast.AnnAssign)
            and isinstance(node.target, ast.Name)
            and node.target.id == "method_to_config"
            and isinstance(node.value, ast.Dict)
        ):
            return {
                ast.literal_eval(key): value.id
                for key, value in zip(node.value.keys, node.value.values)
                if key is not None and isinstance(value, ast.Name)
            }
    raise RuntimeError("Could not find method_to_config")


def class_capabilities() -> dict[str, tuple[str | None, int | None]]:
    classes: dict[str, ast.ClassDef] = {}
    for path in (ROOT / "aphrodite").rglob("*.py"):
        tree = ast.parse(path.read_text())
        for node in tree.body:
            if isinstance(node, ast.ClassDef):
                classes[node.name] = node

    cache: dict[str, tuple[str | None, int | None]] = {}
    visiting: set[str] = set()

    def capability(class_name: str) -> tuple[str | None, int | None]:
        if class_name in cache:
            return cache[class_name]
        if class_name in visiting:
            return (None, None)
        visiting.add(class_name)
        node = classes.get(class_name)
        if node is None:
            visiting.discard(class_name)
            return (None, None)
        for item in node.body:
            if isinstance(item, (ast.FunctionDef, ast.AsyncFunctionDef)) and item.name == "get_min_capability":
                for child in ast.walk(item):
                    if isinstance(child, ast.Return):
                        value = ast.literal_eval(child.value) if child.value is not None else None
                        cache[class_name] = (class_name, value)
                        visiting.discard(class_name)
                        return cache[class_name]
        for base in node.bases:
            if isinstance(base, ast.Name):
                source, value = capability(base.id)
                if source is not None:
                    cache[class_name] = (source, value)
                    visiting.discard(class_name)
                    return cache[class_name]
        cache[class_name] = (None, None)
        visiting.discard(class_name)
        return cache[class_name]

    for class_name in classes:
        capability(class_name)
    return cache


def quantization_reference() -> str:
    methods = quantization_methods()
    config_classes = quantization_config_classes()
    capabilities = class_capabilities()
    declared = {
        platform: set(literal_assignment(path, "supported_quantization")) for platform, path in PLATFORMS.items()
    }
    lines = [
        frontmatter(
            "Quantization support",
            "Quantization methods and platform declarations from the current Sonar source tree.",
        ),
        "<!-- Generated by tools/docs/generate_user_reference.py. Do not edit. -->\n\n",
        "A check mark means that the platform class declares the method. "
        "NVIDIA CUDA accepts all registered methods, but each method can require "
        "a newer compute capability or an optional kernel package. Test your "
        "model on the target device before production use.\n\n",
        "| Method | Minimum NVIDIA capability | AMD ROCm | Intel XPU |\n",
        "| --- | :---: | :---: | :---: |\n",
    ]
    for method in methods:
        config_class = config_classes.get(method, "OnlineQuantizationConfig")
        _, minimum = capabilities.get(config_class, (None, None))
        cuda = f"SM {minimum // 10}.{minimum % 10}" if minimum else "Any supported CUDA GPU"
        rocm = "✓" if method in declared["AMD ROCm"] else "—"
        xpu = "✓" if method in declared["Intel XPU"] else "—"
        lines.append(f"| `{method}` | {cuda} | {rocm} | {xpu} |\n")
    lines.extend(
        [
            "\n## Read the table\n\n",
            "- `✓` means that the platform registry permits the method.\n",
            "- `—` means that the platform does not declare the method.\n",
            "- A permitted method can still require a specific GPU generation.\n",
            "- CPU, Metal, and TPU do not yet publish a complete method list in "
            "their platform classes. Their columns will be added when that "
            "metadata becomes available.\n",
        ]
    )
    return "".join(lines)


def server_arguments() -> str:
    from aphrodite.config import get_attr_docs
    from aphrodite.engine import arg_utils
    from aphrodite.entrypoints.openai.cli_args import (
        BaseFrontendArgs,
        create_parser_for_docs,
    )

    original_needs_help = arg_utils.NEEDS_HELP
    try:
        arg_utils.NEEDS_HELP = True
        arg_utils._compute_kwargs.cache_clear()
        parser = create_parser_for_docs()
    finally:
        arg_utils.NEEDS_HELP = original_needs_help
        arg_utils._compute_kwargs.cache_clear()
    inherited_docs = get_attr_docs(BaseFrontendArgs)

    lines = [
        frontmatter(
            "Server arguments",
            "Command-line arguments for the Sonar OpenAI-compatible server.",
        ),
        "<!-- Generated by tools/docs/generate_user_reference.py. Do not edit. -->\n\n",
        "Run `aphrodite serve --help=<name>` to search for one argument or "
        "configuration group. Run `aphrodite serve --help=all` to read the "
        "same source text in a terminal.\n\n",
    ]
    for group in parser._action_groups:
        actions = [action for action in group._group_actions if action.option_strings]
        if not actions:
            continue
        title = "Sonar configuration" if group.title == "AphroditeConfig" else group.title
        lines.append(f"## {title}\n\n")
        if group.description:
            lines.append(user_facing_text(group.description) + "\n\n")
        for action in actions:
            heading = action.option_strings[0]
            metavar = action.metavar
            if metavar is None and action.nargs != 0:
                metavar = action.dest.upper()
            names = ", ".join(action.option_strings)
            if metavar:
                names += f" {metavar}"
            description = action.help or inherited_docs.get(action.dest, "No description is available.")
            if action.choices:
                choices = ", ".join(f"`{choice}`" for choice in action.choices)
                description += f"\n\nChoices: {choices}."
            if action.default is not None and action.default is not argparse.SUPPRESS:
                description += f"\n\nDefault: `{action.default}`."
            lines.append(f"### `{heading}`\n\n")
            lines.append(f"`{names}`\n\n")
            lines.append(user_facing_text(description) + "\n\n")
    return "".join(lines)


def write(path: Path, content: str, check: bool) -> bool:
    content = "\n".join(line.rstrip() for line in content.rstrip().splitlines()) + "\n"
    if check:
        return path.exists() and path.read_text() == content
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    return True


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    outputs = {
        DOCS / "models.md": model_reference(),
        DOCS / "quantization.md": quantization_reference(),
        DOCS / "server-arguments.md": server_arguments(),
    }
    stale = [str(path.relative_to(ROOT)) for path, content in outputs.items() if not write(path, content, args.check)]
    if stale:
        raise SystemExit("Generated documentation is stale:\n" + "\n".join(stale))


if __name__ == "__main__":
    main()
