name: aphrodite
channels:
  - nvidia
  - nvidia/label/cuda-12.8.1
  - conda-forge
  - defaults
dependencies:
  - python=3.13.*
  - cuda-nvcc=12.8.*
  - cuda-libraries-dev=12.8.*
  - cuda=12.8.*
  - cuda-version=12.8.*
  - nccl
  - cxx-compiler
  - gxx
  - pip
  - git
  - ninja
  - ccache