[mypy]
python_version = 3.10
plugins = pydantic.mypy

ignore_missing_imports = True

files = aphrodite
exclude = aphrodite/modeling/models/

[mypy-pydantic.*]
follow_imports = silent

[mypy-aphrodite.config.utils]
follow_imports = silent

[mypy-aphrodite.inputs,aphrodite.inputs.llm,aphrodite.inputs.engine]
follow_imports = silent

[mypy-aphrodite.distributed,aphrodite.distributed.communication_op,aphrodite.distributed.parallel_state,aphrodite.distributed.utils]
follow_imports = silent

[mypy-aphrodite.model_executor.models.minicpmv]
follow_imports = silent

[mypy-aphrodite.model_executor.layers.linear]
follow_imports = silent

[mypy-aphrodite.model_executor.layers.fused_moe.fused_moe_method_base]
follow_imports = silent

[mypy-aphrodite.omni.data_entry_keys,aphrodite.omni.inputs.data]
follow_imports = silent

[mypy-aphrodite.omni.request]
follow_imports = silent

[mypy-aphrodite.omni.config.transport_fields]
follow_imports = silent
