[mypy]
python_version = 3.10
plugins = pydantic.mypy

ignore_missing_imports = True

files = aphrodite
exclude = aphrodite/modeling/models/

[mypy-pydantic.*]
follow_imports = silent

[mypy-aphrodite.config.utils]
follow_imports = silent
