[pytest]
filterwarnings =
    ignore::DeprecationWarning:pkg_resources.*
    ignore::DeprecationWarning:pyairports.*
    ignore::pytest_asyncio.plugin.PytestDeprecationWarning
    ignore::FutureWarning:xformers.*
    ignore::FutureWarning:torch.*
asyncio_mode = strict
asyncio_default_fixture_loop_scope = function
markers =
    slow_test
    skip_global_cleanup
    core_model: enable this model test in each PR instead of only nightly
    hybrid_model: models that contain mamba layers
    cpu_model: enable this model test in CPU tests
    cpu_test: mark test as CPU-only test
    split: run this test as part of a split
    distributed: run this test only in distributed GPU tests
    optional: optional tests that require --optional
